/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    rooms: Room;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'website-content': WebsiteContent;
  };
  globalsSelect: {
    'website-content': WebsiteContentSelect<false> | WebsiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Mô tả ngắn cho ảnh, dùng cho SEO và accessibility.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: string;
  title: string;
  district: 'Quận 4' | 'Quận 7' | 'Quận 8' | 'Nhà Bè';
  type: 'Duplex' | 'Studio';
  status: 'Trống sẵn' | 'Sắp trống' | 'Đã thuê';
  /**
   * Đơn vị: triệu VND.
   */
  price: number;
  area: string;
  furniture: string;
  address: string;
  desc: string;
  /**
   * Ảnh đại diện hiển thị ngoài danh sách. Nếu để trống, website sẽ dùng đường dẫn ảnh fallback bên dưới.
   */
  photo?: (string | null) | Media;
  /**
   * Không bắt buộc. Chọn nhiều ảnh hoặc video tùy phòng; các media này chỉ hiện khi khách nhấn xem chi tiết.
   */
  gallery?: (string | Media)[] | null;
  /**
   * Ảnh fallback dạng URL/path public, ví dụ /rooms/room-1.svg.
   */
  image?: string | null;
  views?: number | null;
  likes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'rooms';
        value: string | Room;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  title?: T;
  district?: T;
  type?: T;
  status?: T;
  price?: T;
  area?: T;
  furniture?: T;
  address?: T;
  desc?: T;
  photo?: T;
  gallery?: T;
  image?: T;
  views?: T;
  likes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-content".
 */
export interface WebsiteContent {
  id: string;
  seo: {
    title: string;
    description: string;
    siteName: string;
    url: string;
  };
  brand: {
    name: string;
    tagline: string;
  };
  contact: {
    name: string;
    phone: string;
    zalo: string;
    facebook: string;
  };
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  subNavigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  header: {
    callLabel: string;
    zaloLabel: string;
  };
  hero: {
    title: string;
    highlightedTitle: string;
    copy: string;
    primaryLabel: string;
    secondaryLabel: string;
    phoneLabel: string;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  preview: {
    badge: string;
    image: string;
    imageAlt: string;
    title: string;
    price: string;
    location: string;
    socialProof: string;
    status: string;
  };
  filters: {
    title: string;
    copy: string;
    resetLabel: string;
    keywordLabel: string;
    keywordPlaceholder: string;
    priceLabel: string;
    districtLabel: string;
    typeLabel: string;
    statusLabel: string;
    searchLabel: string;
    quickFiltersLabel: string;
    priceRanges?:
      | {
          label: string;
          value: string;
          low: number;
          high: number;
          id?: string | null;
        }[]
      | null;
    quickFilters?:
      | {
          label: string;
          group: 'district' | 'type' | 'status' | 'price';
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  trustStrip?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  listings: {
    title: string;
    resultPrefix: string;
    resultSuffix: string;
    sortLabel: string;
    emptyTitle: string;
    emptyCopy: string;
    likeLabel: string;
    likedLabel: string;
    messageLabel: string;
    contactLabel: string;
  };
  contactSection: {
    eyebrow: string;
    title: string;
    copy: string;
    zaloLabel: string;
    facebookLabel: string;
  };
  mobileContact: {
    ariaLabel: string;
    zaloLabel: string;
    callLabel: string;
    facebookLabel: string;
  };
  footer: {
    text: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-content_select".
 */
export interface WebsiteContentSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        siteName?: T;
        url?: T;
      };
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        phone?: T;
        zalo?: T;
        facebook?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  subNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  header?:
    | T
    | {
        callLabel?: T;
        zaloLabel?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        highlightedTitle?: T;
        copy?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
        phoneLabel?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  preview?:
    | T
    | {
        badge?: T;
        image?: T;
        imageAlt?: T;
        title?: T;
        price?: T;
        location?: T;
        socialProof?: T;
        status?: T;
      };
  filters?:
    | T
    | {
        title?: T;
        copy?: T;
        resetLabel?: T;
        keywordLabel?: T;
        keywordPlaceholder?: T;
        priceLabel?: T;
        districtLabel?: T;
        typeLabel?: T;
        statusLabel?: T;
        searchLabel?: T;
        quickFiltersLabel?: T;
        priceRanges?:
          | T
          | {
              label?: T;
              value?: T;
              low?: T;
              high?: T;
              id?: T;
            };
        quickFilters?:
          | T
          | {
              label?: T;
              group?: T;
              value?: T;
              id?: T;
            };
      };
  trustStrip?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  listings?:
    | T
    | {
        title?: T;
        resultPrefix?: T;
        resultSuffix?: T;
        sortLabel?: T;
        emptyTitle?: T;
        emptyCopy?: T;
        likeLabel?: T;
        likedLabel?: T;
        messageLabel?: T;
        contactLabel?: T;
      };
  contactSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        copy?: T;
        zaloLabel?: T;
        facebookLabel?: T;
      };
  mobileContact?:
    | T
    | {
        ariaLabel?: T;
        zaloLabel?: T;
        callLabel?: T;
        facebookLabel?: T;
      };
  footer?:
    | T
    | {
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}